name: Development Deploy Lambda Function

on:
  push:
    branches: [develop]
  workflow_dispatch:
    
env:
    LAMBDA_FUNCTION_NAME: <lambda_function_name>

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      # Build Lambda Function
      - name: Build Lambda Function
        run: GOOS=linux CGO_ENABLED=0 go build cmd/main.go; zip addLambdaFunction.zip main; ls;

      - name: Execute Test
        run: go test -v ./...

      - name: Configure AWS credentials from Development account
        uses: aws-actions/configure-aws-credentials@v2
        with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: ${{ secrets.AWS_REGION }}
            role-session-name: SessionRetrieveAndValidateAPIKey

      - name: Development - Upload lambda function
        run: aws lambda update-function-code --function-name  ${{ env.LAMBDA_FUNCTION_NAME }} --zip-file fileb://addLambdaFunction.zip
